### ISSUE TITLE
DOCUMENTATION OF PLANNED SYSTEM WITHIN 8/11

### ISSUE THREAD

**Issue by Chr1stian** [IT2810/it2810-webutvikling-h17-prosjekt-4-group-37#9]
Legg ut dokumentasjon av det planlagte systemet innen 8/11 på GitHub. Beskriv applikasjonen, data, planlagt implementasjon, valg av løsning etc.  Dette skal brukes for å evaluere/gi tilbakemeldinger på arkitektur og overordent design. Det er deltagelse i denne evalueringen som teller.  Evaluering av arkitektur og design av systemet gjøres 9/11 (det er deltagelse i evalueringen som teller og i sluttevalueringen blir det sjekket om dere følger relevante råd).

**Comment by oystpoyst** [comment]
Jeg kan fikse skisser.

**Comment by Chr1stian** [comment]
Kan sikkert få til en beskrivelse av MVC med noe fancy ord og illustrasjoner
